import type { Localized } from "./types";

export type Locale = "fr" | "ar";

type Dict = { [key: string]: string | Dict };

/**
 * Full UI copy in French and Arabic.
 * Arabic renders with dir="rtl" — layout uses logical CSS properties.
 */

const fr: Dict = {
  skip: "Aller au contenu principal",
  concept: "Concept",
  lang: { label: "Langue", fr: "Français", ar: "العربية" },
  nav: {
    home: "Accueil",
    destinations: "Destinations",
    offres: "Offres",
    billets: "Billets",
    hotels: "Hôtels",
    about: "À propos",
    contact: "Contact",
    cta: "Demander une offre",
  },
  header: { cityTag: "Béjaïa · Algérie" },
  hero: {
    badge: "Agence de voyages à Béjaïa",
    title: "Votre prochain voyage commence ici.",
    subtitle:
      "Fly Voyages Algérie vous accompagne à Béjaïa dans la préparation de votre voyage : destination, billets d'avion, hébergement et séjours organisés.",
    ctaPrimary: "Préparer mon voyage",
    ctaSecondary: "Nous contacter",
    note: "Aucune réservation automatique : vous déposez une demande, un conseiller vous recontacte avec une proposition.",
  },
  search: {
    title: "Où souhaitez-vous partir ?",
    hint: "Indiquez vos grandes lignes — nous faisons le reste.",
    tabs: { voyage: "Voyage", vol: "Vol", hotel: "Hôtel", sejour: "Séjour" },
    destination: "Destination",
    destinationPh: "Ex. Istanbul, Paris, Dubaï…",
    depart: "Date de départ",
    retour: "Date de retour",
    checkIn: "Arrivée",
    checkOut: "Départ",
    from: "Départ",
    to: "Arrivée",
    travelers: "Voyageurs",
    fromOptions: {
      bja: "Béjaïa (IKN)",
      alg: "Alger (ALG)",
      orn: "Oran (ORN)",
      czl: "Constantine (CZL)",
      other: "Autre",
    },
    cta: {
      voyage: "Recevoir une proposition",
      vol: "Demander un billet",
      hotel: "Demander un hôtel",
      sejour: "Recevoir une proposition",
    },
  },
  common: {
    discover: "Découvrir",
    requestOffer: "Demander une offre",
    talk: "Parler à Fly Voyages",
    phone: "Appeler",
    whatsapp: "WhatsApp",
    toConfirm: "à confirmer",
    onDemand: "sur demande",
  },
  styles: {
    sejour: "Séjour",
    famille: "Famille",
    couple: "Couple",
    citybreak: "City break",
    plage: "Plage",
    aventure: "Aventure",
  },
  regions: {
    europe: "Europe",
    turquie: "Turquie",
    "moyen-orient": "Moyen-Orient",
    afrique: "Afrique",
  },
  destinations: {
    overline: "Destinations",
    title: "Inspirations pour votre prochain départ",
    subtitle:
      "Une sélection de destinations de démonstration, à adapter aux véritables offres de l'agence.",
    all: "Toutes",
    allCta: "Voir toutes les destinations",
    idealFor: "Idéal pour",
    whyTitle: "Pourquoi y aller",
    periods: "Périodes conseillées",
    discoverTitle: "À découvrir",
    stylesTitle: "Styles de voyage",
    related: "Autres destinations",
    breadcrumb: "Destinations",
  },
  offers: {
    overline: "Offres & séjours",
    title: "Des séjours prêts à demander",
    subtitle:
      "Formats de séjours présentés à titre de concept. Prix sur demande : chaque offre est ajustée à votre projet.",
    price: "Prix sur demande",
    duration: "Durée",
    type: "Type",
    hotel: "Hébergement",
    departure: "Départ",
    cta: "Demander cette offre",
    highlights: "Points forts",
  },
  why: {
    overline: "Pourquoi Fly Voyages",
    title: "Une agence de proximité, un accompagnement simple",
    i1t: "À Béjaïa, près de chez vous",
    i1d:
      "Rue Frères Tabet, en plein centre : passez nous voir, appelez ou écrivez-nous sur WhatsApp. Une vraie agence de proximité.",
    i2t: "Billetterie, séjours et circuits",
    i2d:
      "Vos projets de voyage, billets d'avion, séjours et circuits sont préparés par une équipe, pas par un automate.",
    i3t: "Une réponse rapide",
    i3d:
      "Vous déposez une demande en deux minutes. Notre équipe vous recontacte avec une proposition adaptée à vos dates et à votre budget.",
    i4t: "Un interlocuteur, du départ au retour",
    i4d:
      "Le même conseiller suit votre dossier : information claire, aide en cas de changement, disponibilité pendant vos démarches.",
  },
  band: {
    overline: "Billetterie & hôtels",
    title: "Un vol ou un hôtel à organiser ?",
    subtitle:
      "Deux demandes simples, un seul interlocuteur : notre équipe prépare la proposition qui correspond à votre budget.",
    ctaFlight: "Demander un billet",
    ctaHotel: "Demander un hôtel",
  },
  inspiration: {
    overline: "Inspiration",
    title: "Des horizons à portée de main",
    subtitle: "Quelques destinations qui reviennent souvent dans nos conversations.",
    cta: "Explorer les destinations",
  },
  whatsapp: {
    overline: "WhatsApp",
    title: "Une question ? Écrivez-nous.",
    text: "Le plus simple pour démarrer : un message WhatsApp. Dites-nous où vous aimeriez partir et quand, on s'occupe du reste.",
    cta: "Ouvrir WhatsApp",
    phoneNote: "Ou par téléphone : 0550 06 06 20",
  },
  location: {
    overline: "Nous trouver",
    title: "Nous trouver à Béjaïa",
    addressTitle: "Adresse",
    phoneLabel: "Téléphone",
    waLabel: "WhatsApp",
    hours: "Horaires d'ouverture",
    hoursTBC: "À confirmer",
    mapNote: "Vue de la ville de Béjaïa — l'adresse exacte sur la carte sera confirmée avec l'agence.",
    mapError:
      "La carte n'a pas pu être chargée. Adresse : Rue Frères Tabet, Béjaïa 06000, Algérie.",
  },
  footer: {
    blurb:
      "Fly Voyages Algérie — agence de voyages et de billetterie aérienne à Béjaïa. Nous vous accompagnons dans la préparation de vos projets de voyage.",
    explore: "Explorer",
    contact: "Contact",
    hours: "Horaires",
    hoursTBC: "À confirmer",
    concept:
      "Site concept préparé pour Fly Voyages Algérie — services, horaires et offres détaillés seront confirmés avec l'agence.",
    rights: "© 2026 Fly Voyages Algérie. Tous droits réservés.",
    cityLine: "Béjaïa · Algérie",
  },
  mobileCta: { whatsapp: "WhatsApp", call: "Appeler", offer: "Offre" },
  wa: {
    general: "Bonjour Fly Voyages, je souhaite préparer un voyage.",
    destination: "Bonjour Fly Voyages, je souhaite avoir une offre pour %DEST%.",
    flight: "Bonjour Fly Voyages, je souhaite demander un billet de %FROM% vers %TO%.",
    hotel: "Bonjour Fly Voyages, je souhaite demander un hôtel à %DEST%.",
    offer: "Bonjour Fly Voyages, je suis intéressé par l'offre « %OFFER% ».",
  },
  forms: {
    name: "Nom complet",
    namePh: "Votre nom et prénom",
    phone: "Téléphone",
    phonePh: "Ex. 0550 06 06 20",
    whatsapp: "WhatsApp (facultatif)",
    whatsappPh: "Même numéro si besoin",
    message: "Message (facultatif)",
    messagePh: "Précisez ce que vous souhaitez…",
    submitting: "Envoi en cours…",
    successTitle: "Demande bien reçue",
    successText:
      "Merci ! Notre équipe à Béjaïa vous recontacte rapidement au numéro indiqué.",
    successWa: "Écrire sur WhatsApp",
    successPhone: "ou appeler le %PHONE%",
    successHome: "Retour à l'accueil",
    errRequired: "Ce champ est requis",
    errPhone: "Numéro de téléphone invalide",
    errDates: "Vérifiez les dates : le retour doit être après le départ.",
    errSubmit:
      "Une erreur est survenue lors de l'envoi. Veuillez réessayer, ou contactez-nous directement par téléphone et WhatsApp.",
  },
  demande: {
    overline: "Demande de voyage",
    title: "Préparez votre voyage en quelques minutes",
    subtitle:
      "Décrivez votre projet : destination, dates, budget. Notre équipe vous recontacte avec une proposition personnalisée, sans engagement.",
    destination: "Destination",
    destinationPh: "Ex. Istanbul, Antalya, Paris…",
    depart: "Date de départ",
    retour: "Date de retour (facultatif)",
    travelers: "Nombre de voyageurs",
    type: "Type de voyage",
    budget: "Budget indicatif (facultatif)",
    prefs: "Préférences (facultatif)",
    prefsPh: "Classe, hébergement, restaurants, contraintes particulières…",
    types: {
      sejour: "Séjour / vacances",
      business: "Business",
      couple: "En couple",
      famille: "En famille",
      groupe: "En groupe",
      omra: "Omra",
      autre: "Autre",
    },
    budgets: {
      b1: "Moins de 50 000 DA",
      b2: "50 000 – 100 000 DA",
      b3: "100 000 – 200 000 DA",
      b4: "Plus de 200 000 DA",
      b5: "À discuter",
    },
    cta: "Recevoir une proposition",
    sideTitle: "Comment ça se passe ?",
    side1t: "Vous envoyez votre demande",
    side1d: "Deux minutes suffisent : destination, dates et quelques préférences.",
    side2t: "Un conseiller vous recontacte",
    side2d: "Par téléphone ou WhatsApp, pour préciser votre projet.",
    side3t: "Vous recevez une proposition",
    side3d: "Vol, hébergement et rythme du séjour, ajustés à votre budget.",
    sideWa: "Vous préférez discuter tout de suite ?",
  },
  billets: {
    overline: "Billetterie aérienne",
    title: "Besoin d'un billet d'avion ?",
    subtitle:
      "Indiquez votre trajet et vos dates : nous vérifions les vols disponibles et revenons vers vous avec les meilleures options.",
    from: "Départ",
    to: "Destination",
    toPh: "Ex. Istanbul (IST)",
    dateAllez: "Date aller",
    dateRetour: "Date retour (facultatif)",
    roundTrip: "Aller-retour",
    travelers: "Nombre de voyageurs",
    classe: "Classe",
    classes: {
      eco: "Économique",
      flex: "Économique flexible",
      biz: "Affaire",
      first: "Première",
    },
    cta: "Demander un billet",
    note: "Le site ne vend pas directement de billets : vous recevez une proposition détaillée avec les vols disponibles et leurs tarifs.",
  },
  hotels: {
    overline: "Hébergement",
    title: "Trouvez l'hébergement qui correspond à votre voyage",
    subtitle:
      "Hôtel, résidence ou maison d'hôtes : donnez-nous vos dates et vos préférences, nous sélectionnons les options disponibles pour vous.",
    destination: "Destination",
    destinationPh: "Ex. Istanbul, Antalya, Paris…",
    checkIn: "Date d'arrivée",
    checkOut: "Date de départ",
    persons: "Nombre de personnes",
    type: "Type d'hébergement",
    types: {
      hotel: "Hôtel",
      residence: "Résidence / appartement",
      riad: "Maison d'hôtes / Riad",
      autre: "Autre",
    },
    budget: "Budget (facultatif)",
    prefs: "Préférences (facultatif)",
    prefsPh: "Chambre double, petit-déjeuner, vue mer…",
    cta: "Demander un hôtel",
  },
  aPropos: {
    overline: "À propos",
    title: "Votre agence de voyages à Béjaïa",
    intro:
      "Fly Voyages Algérie est une agence de voyages et de billetterie aérienne installée à Béjaïa, rue Frères Tabet. Nous vous accompagnons dans la préparation de vos projets de voyage — du premier contact jusqu'au jour du départ.",
    roleTitle: "Notre rôle",
    roleText:
      "Sélectionner les bonnes options, vérifier les disponibilités, préparer une proposition claire : vol, hébergement, rythme du séjour. Vous gardez la main sur chaque décision ; nous gérons les détails.",
    stepsTitle: "Comment ça marche",
    s1t: "Vous partagez votre projet",
    s1d: "Destination, dates, budget : tout part d'une simple demande.",
    s2t: "Nous préparons une proposition",
    s2d: "Options de vols, d'hébergement et de programme, présentées clairement.",
    s3t: "Vous validez ce qui vous convient",
    s3d: "Nous ajustons jusqu'à ce que chaque détail vous convienne.",
    s4t: "Vous partez l'esprit tranquille",
    s4d: "Les détails sont coordonnés avant votre départ.",
    contactTitle: "Discutons de votre projet",
    contactText: "Appelez, écrivez sur WhatsApp ou passez nous voir à Béjaïa.",
    note: "Ce site est un concept préparé pour Fly Voyages Algérie. Les services détaillés, horaires et offres seront confirmés avec l'agence avant la mise en ligne.",
  },
  contact: {
    overline: "Contact",
    title: "Parlons de votre voyage",
    subtitle: "Nous sommes à votre écoute par téléphone, WhatsApp ou sur place à Béjaïa.",
    formTitle: "Envoyez-nous un message",
    cta: "Envoyer le message",
  },
  notFound: {
    title: "Page introuvable",
    text: "La page que vous cherchez n'existe pas ou a été déplacée.",
    cta: "Retour à l'accueil",
  },
};

const ar: Dict = {
  skip: "الانتقال إلى المحتوى الرئيسي",
  concept: "مفهوم",
  lang: { label: "اللغة", fr: "Français", ar: "العربية" },
  nav: {
    home: "الرئيسية",
    destinations: "الوجهات",
    offres: "العروض",
    billets: "التذاكر",
    hotels: "الفنادق",
    about: "من نحن",
    contact: "اتصل بنا",
    cta: "اطلب عرضًا",
  },
  header: { cityTag: "بجاية · الجزائر" },
  hero: {
    badge: "مكتب سياحة وسفر في بجاية",
    title: "رحلتك القادمة تبدأ من هنا.",
    subtitle:
      "فلاي فويارات الجزائر ترافقك في بجاية لتنظيم رحلتك: الوجهة، تذاكر الطيران، الإقامة وبرنامج السفر.",
    ctaPrimary: "جهّز رحلتي",
    ctaSecondary: "اتصل بنا",
    note: "لا توجد حجوزات آلية: تُرسل طلبك، ويتصل بك مستشارنا باقتراح مخصص.",
  },
  search: {
    title: "إلى أين تريد السفر؟",
    hint: "أعطنا الخطوط الكبرى — ونتولى الباقي.",
    tabs: { voyage: "رحلة", vol: "طيران", hotel: "فندق", sejour: "إقامة" },
    destination: "الوجهة",
    destinationPh: "مثال: إسطنبول، باريس، دبي…",
    depart: "تاريخ المغادرة",
    retour: "تاريخ العودة",
    checkIn: "الوصول",
    checkOut: "المغادرة",
    from: "من",
    to: "إلى",
    travelers: "عدد المسافرين",
    fromOptions: {
      bja: "بجاية (IKN)",
      alg: "الجزائر (ALG)",
      orn: "وهران (ORN)",
      czl: "قسنطينة (CZL)",
      other: "أخرى",
    },
    cta: {
      voyage: "استلم اقتراحًا",
      vol: "اطلب تذكرة",
      hotel: "اطلب فندقًا",
      sejour: "استلم اقتراحًا",
    },
  },
  common: {
    discover: "اكتشف",
    requestOffer: "اطلب عرضًا",
    talk: "تحدث إلى فلاي فويارات",
    phone: "اتصل",
    whatsapp: "واتساب",
    toConfirm: "يُحدَّد",
    onDemand: "حسب الطلب",
  },
  styles: {
    sejour: "إقامة",
    famille: "عائلة",
    couple: "زوجين",
    citybreak: "نهاية أسبوع",
    plage: "شاطئ",
    aventure: "مغامرة",
  },
  regions: {
    europe: "أوروبا",
    turquie: "تركيا",
    "moyen-orient": "الشرق الأوسط",
    afrique: "أفريقيا",
  },
  destinations: {
    overline: "الوجهات",
    title: "أفكار لرحلتك القادمة",
    subtitle: "مختارات وجهات توضيحية، تُكيّف مع العروض الحقيقية للمكتب.",
    all: "الكل",
    allCta: "استعرض كل الوجهات",
    idealFor: "مثالية لـ",
    whyTitle: "لماذا تزورها؟",
    periods: "مواسم موصى بها",
    discoverTitle: "ما الذي تكتشفه",
    stylesTitle: "أنماط السفر",
    related: "وجهات أخرى",
    breadcrumb: "الوجهات",
  },
  offers: {
    overline: "العروض والإقامات",
    title: "إقامات جاهزة للطلب",
    subtitle:
      "صيغ إقامات معروضة لأغراض العرض. السعر حسب الطلب — كل عرض يُعدَّل حسب مشروعك.",
    price: "السعر حسب الطلب",
    duration: "المدة",
    type: "النوع",
    hotel: "الإقامة",
    departure: "المغادرة",
    cta: "اطلب هذا العرض",
    highlights: "نقاط القوة",
  },
  why: {
    overline: "لماذا فلاي فويارات",
    title: "مكتب قريب إليك، ومرافقة بسيطة",
    i1t: "في بجاية، بالقرب منك",
    i1d:
      "في شارع الإخوة طابت وسط المدينة: زورونا، اتصل أو أرسل لنا على واتساب. مكتب قريب بكل ما للكلمة من معنى.",
    i2t: "تذاكر، إقامات ورحلات",
    i2d:
      "تُحضَّر مشاريع السفر وتذاكر الطيران والإقامات والرحلات من طرف فريق مختص، لا من طرف نظام آلي.",
    i3t: "ردّ سريع",
    i3d:
      "تُقدِم طلبك في دقيقتين، ويتصل بك فريقنا باقتراح يناسب تاريخك وميزانيتك.",
    i4t: "متحدّث واحد، من الذهاب إلى العودة",
    i4d:
      "نفس المستشار يتابع ملفك: معلومات واضحة، ومساعدة عند أي تغيير، ومتابعة لخطواتك.",
  },
  band: {
    overline: "التذاكر والفنادق",
    title: "طيران أو فندق لتنظيمه؟",
    subtitle: "طلبان بسيطان، ومتحدّث واحد: فريقنا يعدّ الاقتراح المناسب لميزانيتك.",
    ctaFlight: "اطلب تذكرة",
    ctaHotel: "اطلب فندقًا",
  },
  inspiration: {
    overline: "إلهام",
    title: "آفاق في متناول اليد",
    subtitle: "بعض الوجهات التي تتكرر في أحاديثنا.",
    cta: "استكشف الوجهات",
  },
  whatsapp: {
    overline: "واتساب",
    title: "لديك سؤال؟ راسلنا.",
    text: "الأسهل للبدء: رسالة واتساب. أخبرنا إلى أين تحب الذهاب ومتى، ونتولى الباقي.",
    cta: "افتح واتساب",
    phoneNote: "أو عبر الهاتف: 0550 06 06 20",
  },
  location: {
    overline: "العنوان",
    title: "تجدنا في بجاية",
    addressTitle: "العنوان",
    phoneLabel: "هاتف",
    waLabel: "واتساب",
    hours: "ساعات العمل",
    hoursTBC: "تُحدَّد لاحقًا",
    mapNote: "مظهر لمدينة بجاية — العنوان الدقيق على الخريطة يُؤكد مع المكتب.",
    mapError: "تعذّر تحميل الخريطة. العنوان: شارع الإخوة طابت، بجاية 06000، الجزائر.",
  },
  footer: {
    blurb:
      "فلاي فويارات الجزائر — مكتب سياحة وسفر وتذاكر طيران في بجاية. نرافقك في تجهيز مشاريع السفر.",
    explore: "اكتشف",
    contact: "اتصل بنا",
    hours: "ساعات العمل",
    hoursTBC: "تُحدَّد لاحقًا",
    concept:
      "موقع تجريبي أُعدّ لفلاي فويارات الجزائر — الخدمات والساعات والعروض التفصيلية تُؤكد مع المكتب.",
    rights: "© 2026 فلاي فويارات الجزائر. جميع الحقوق محفوظة.",
    cityLine: "بجاية · الجزائر",
  },
  mobileCta: { whatsapp: "واتساب", call: "اتصل", offer: "عرض" },
  wa: {
    general: "مرحباً فلاي فويارات، أودّ تنظيم رحلة.",
    destination: "مرحباً فلاي فويارات، أودّ الحصول على عرض للوجهة %DEST%.",
    flight: "مرحباً فلاي فويارات، أودّ طلب تذكرة من %FROM% إلى %TO%.",
    hotel: "مرحباً فلاي فويارات، أودّ طلب فندق في %DEST%.",
    offer: "مرحباً فلاي فويارات، أهتم بعرض « %OFFER% ».",
  },
  forms: {
    name: "الاسم الكامل",
    namePh: "اسمك الكامل",
    phone: "الهاتف",
    phonePh: "مثال: 0550 06 06 20",
    whatsapp: "واتساب (اختياري)",
    whatsappPh: "نفس الرقم إن لزم",
    message: "رسالة (اختياري)",
    messagePh: "حدّد طلبك…",
    submitting: "جارٍ الإرسال…",
    successTitle: "تمّ استلام طلبك",
    successText: "شكرًا! سيتصل بك فريقنا في بجاية قريبًا على الرقم المذكور.",
    successWa: "راسلنا على واتساب",
    successPhone: "أو اتصل على %PHONE%",
    successHome: "العودة إلى الرئيسية",
    errRequired: "هذا الحقل مطلوب",
    errPhone: "رقم هاتف غير صالح",
    errDates: "تحقق من التواريخ: يجب أن يكون تاريخ العودة بعد تاريخ المغادرة.",
    errSubmit:
      "حدث خطأ أثناء الإرسال. حاول مرة أخرى، أو راسلنا مباشرة عبر الهاتف أو واتساب.",
  },
  demande: {
    overline: "طلب رحلة",
    title: "جهّز رحلتك في دقائق",
    subtitle:
      "صفّ مشروعك: الوجهة، التواريخ، الميزانية. سيتصل بك فريقنا باقتراح مخصص، دون أي التزام.",
    destination: "الوجهة",
    destinationPh: "مثال: إسطنبول، أنطاليا، باريس…",
    depart: "تاريخ المغادرة",
    retour: "تاريخ العودة (اختياري)",
    travelers: "عدد المسافرين",
    type: "نوع الرحلة",
    budget: "ميزانية استرشادية (اختياري)",
    prefs: "تفضيلات (اختياري)",
    prefsPh: "الفئة، الإقامة، المطاعم، متطلبات خاصة…",
    types: {
      sejour: "إقامة / عطل",
      business: "أعمال",
      couple: "لزوجين",
      famille: "لعائلة",
      groupe: "لمجموعة",
      omra: "عمرة",
      autre: "آخر",
    },
    budgets: {
      b1: "أقل من 50 000 دج",
      b2: "50 000 – 100 000 دج",
      b3: "100 000 – 200 000 دج",
      b4: "أكثر من 200 000 دج",
      b5: "يُناقش",
    },
    cta: "استلم اقتراحًا",
    sideTitle: "كيف تتم العملية؟",
    side1t: "تُقدِم طلبك",
    side1d: "دقيقتان تكفيان: الوجهة، التواريخ، وبعض التفضيلات.",
    side2t: "مستشارنا يتصل بك",
    side2d: "عبر الهاتف أو واتساب، لتفصيل مشروعك.",
    side3t: "تستلم اقتراحًا",
    side3d: "الطيران، الإقامة، وإيقاع الرحلة، حسب ميزانيتك.",
    sideWa: "تفضّل التحدث فورًا؟",
  },
  billets: {
    overline: "تذاكر الطيران",
    title: "تحتاج إلى تذكرة طيران؟",
    subtitle:
      "حدّد رحلتك وتواريخك: نتحقق من الرحلات المتاحة ونعود إليك بأفضل الخيارات.",
    from: "المغادرة",
    to: "الوجهة",
    toPh: "مثال: إسطنبول (IST)",
    dateAllez: "تاريخ الذهاب",
    dateRetour: "تاريخ العودة (اختياري)",
    roundTrip: "ذهاب وعودة",
    travelers: "عدد المسافرين",
    classe: "الفئة",
    classes: {
      eco: "اقتصادية",
      flex: "اقتصادية مرنة",
      biz: "أعمال",
      first: "أولى",
    },
    cta: "اطلب تذكرة",
    note: "الموقع لا يبيع التذاكر مباشرة: ستصلك تفاصيل الرحلات المتوفرة والتعرفة من فريقنا.",
  },
  hotels: {
    overline: "الإقامة",
    title: "اعثر على الإقامة المناسبة لرحلتك",
    subtitle:
      "فندق، شقة، أو ضيافة: أعطنا تواريخك وتفضيلاتك، ونختار لك الخيارات المتاحة.",
    destination: "الوجهة",
    destinationPh: "مثال: إسطنبول، أنطاليا، باريس…",
    checkIn: "تاريخ الوصول",
    checkOut: "تاريخ المغادرة",
    persons: "عدد الأشخاص",
    type: "نوع الإقامة",
    types: {
      hotel: "فندق",
      residence: "شقة / إقامة",
      riad: "ضيافة / ريفاد",
      autre: "آخر",
    },
    budget: "الميزانية (اختياري)",
    prefs: "تفضيلات (اختياري)",
    prefsPh: "غرفة مزدوجة، فطور، إطلالة على البحر…",
    cta: "اطلب فندقًا",
  },
  aPropos: {
    overline: "من نحن",
    title: "مكتبك للسياحة والسفر في بجاية",
    intro:
      "فلاي فويارات الجزائر مكتب سياحة وسفر وتذاكر طيران يوجد في بجاية، شارع الإخوة طابت. نرافقك في تجهيز مشاريع السفر — من أول تواصل إلى يوم المغادرة.",
    roleTitle: "دورنا",
    roleText:
      "اختيار الخيارات الصحيحة، التحقق من التوفر، وإعداد اقتراح واضح: الطيران، الإقامة، وإيقاع الرحلة. أنت تحتفظ بالقرار في كل خطوة، ونحن نتولى التفاصيل.",
    stepsTitle: "كيف تتم العملية؟",
    s1t: "تشاركنا مشروعك",
    s1d: "الوجهة، التواريخ، الميزانية: كل شيء يبدأ بطلب بسيط.",
    s2t: "نعدّ لك اقتراحًا",
    s2d: "خيارات الطيران، الإقامة، وبرنامج الرحلة، بشكل واضح.",
    s3t: "تؤكد ما يناسبك",
    s3d: "نعدّل حتى يناسبك كل تفصيل.",
    s4t: "تسافر مطمئنًا",
    s4d: "التفاصيل تنسّق قبل مغادرتك.",
    contactTitle: "لنتحدث عن مشروعك",
    contactText: "اتصل، راسلنا على واتساب، أو زورونا في بجاية.",
    note: "هذا الموقع عرض تمهيدي أُعدّ لفلاي فويارات الجزائر. الخدمات التفصيلية والساعات والعروض تُؤكد مع المكتب قبل الإطلاق.",
  },
  contact: {
    overline: "اتصل بنا",
    title: "لنتحدث عن رحلتك",
    subtitle: "نحن في خدمتك عبر الهاتف أو واتساب، أو حضوريًا في بجاية.",
    formTitle: "أرسل لنا رسالة",
    cta: "أرسل الرسالة",
  },
  notFound: {
    title: "الصفحة غير موجودة",
    text: "الصفحة التي تبحث عنها غير موجودة أو تم نقلها.",
    cta: "العودة إلى الرئيسية",
  },
};

export const dictionaries: Record<Locale, Dict> = { fr, ar };

/** Resolve a dot-path ("nav.home") in the given locale, falling back to French. */
export function t(locale: Locale, path: string): string {
  const walk = (d: Dict): unknown =>
    path.split(".").reduce<unknown>((o, k) => {
      if (o && typeof o === "object") return (o as Dict)[k];
      return undefined;
    }, d);
  const value = walk(dictionaries[locale]) ?? walk(dictionaries.fr);
  return typeof value === "string" ? value : path;
}

/** Pick the localized value for the active locale. */
export function pick(locale: Locale, value: Localized): string {
  return value[locale] ?? value.fr;
}
